# Github Actions  Trigger Python Script

name: divdscrape to csv
# Controls when the workflow will run
on:
  workflow_dispatch         #manual trigger

  #schedule:
    #- cron: "58 9 1 1-12 *"
    # Triggers the workflow every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: pip install -r requirements.txt
      
      - name: execute py script # run divdscrape-gsheet.py
        run: python electricitytariff-scrape.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
